GPU=0

user=jingmins

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=l211pretrain_KG wandb.id=l211pretrain_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=l221pretrain_KG wandb.id=l221pretrain_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=l221pretrainnormal_KG wandb.id=l221pretrainnormal_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=0 zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
###
###
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=l211pretrain_KG_ftSG wandb.id=l211pretrain_KG_ftSG reload_model=checkpoint/jingmins/dumped/scaling/l211pretrain_KG/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=l221pretrain_KG_ftSG wandb.id=l221pretrain_KG_ftSG reload_model=checkpoint/jingmins/dumped/scaling/l221pretrain_KG/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=l221pretrainnormal_KG_ftSG wandb.id=l221pretrainnormal_KG_ftSG reload_model=checkpoint/jingmins/dumped/scaling/l221pretrainnormal_KG/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_KG/checkpoint.pth exp_name=scaling exp_id=l211pretrain_KGev wandb.id=l211pretrain_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_KG/checkpoint.pth exp_name=scaling exp_id=l221pretrain_KGev wandb.id=21pretrain_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal_KG/checkpoint.pth exp_name=scaling exp_id=l221pretrainnormal_KGev wandb.id=l221pretrainnormal_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0  zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/11pretrain_KG_ftSG/checkpoint.pth exp_name=comparison exp_id=11pretrain_KG_ftSGev wandb.id=11pretrain_KG_ftSGev eval_only=true   train_size=81000 train_size_get=81000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/21pretrain_KG_ftSG/checkpoint.pth exp_name=comparison exp_id=21pretrain_KG_ftSGev wandb.id=21pretrain_KG_ftSGev eval_only=true   train_size=81000 train_size_get=81000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/21pretrainnormal_KG_ftSG/checkpoint.pth exp_name=comparison exp_id=21pretrainnormal_KG_ftSGev wandb.id=21pretrainnormal_KG_ftSGev eval_only=true   train_size=81000 train_size_get=81000 eval_size=4000 eval_size_get=4000  model.no_text=0  zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_KG wandb.id=fno_KG exp_name=comparison train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_KG wandb.id=deeponet_KG exp_name=comparison train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_KG_ftSG wandb.id=fno_KG_ftSG exp_name=comparison reload_model=checkpoint/jingmins/dumped/comparison/fno_KG/checkpoint.pth train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_KG_ftSG wandb.id=deeponet_KG_ftSG exp_name=comparison reload_model=checkpoint/jingmins/dumped/comparison/deeponet_KG/checkpoint.pth train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1 batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/fno_KG/checkpoint.pth exp_name=comparison exp_id=fno_KGev wandb.id=fno_KGev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model=fno data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/deeponet_KG/checkpoint.pth exp_name=comparison exp_id=deeponet_KGev wandb.id=deeponet_KGev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model=deeponet  data.input_len=2 data.input_step=1  noise=0
###
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/fno_KG_ftSG/checkpoint.pth exp_name=comparison exp_id=fno_KG_ftSGev wandb.id=fno_KG_ftSGev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon] model=fno data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/comparison/deeponet_KG_ftSG/checkpoint.pth exp_name=comparison exp_id=deeponet_KG_ftSGev wandb.id=deeponet_KG_ftSGev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model=deeponet data.input_len=2 data.input_step=1  noise=0
#

#######################

train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]
eval_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain_KG wandb.id=11pretrain_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain_KG wandb.id=21pretrain_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal_KG wandb.id=21pretrainnormal_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=0 zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
####
###
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain_KG_ftSG wandb.id=11pretrain_KG_ftSG reload_model=checkpoint/jingmins/dumped/scaling/11pretrain_KG/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain_KG_ftSG wandb.id=21pretrain_KG_ftSG reload_model=checkpoint/jingmins/dumped/scaling/21pretrain_KG/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal_KG_ftSG wandb.id=21pretrainnormal_KG_ftSG reload_model=checkpoint/jingmins/dumped/scaling/21pretrainnormal_KG/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_KG/checkpoint.pth exp_name=scaling exp_id=11pretrain_KGev wandb.id=11pretrain_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_KG/checkpoint.pth exp_name=scaling exp_id=21pretrain_KGev wandb.id=21pretrain_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal_KG/checkpoint.pth exp_name=scaling exp_id=21pretrainnormal_KGev wandb.id=21pretrainnormal_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0  zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
###
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_KG_ftSG/checkpoint.pth exp_name=scaling exp_id=11pretrain_KG_ftSGev wandb.id=11pretrain_KG_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_KG_ftSG/checkpoint.pth exp_name=scaling exp_id=21pretrain_KG_ftSGev wandb.id=21pretrain_KG_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal_KG_ftSG/checkpoint.pth exp_name=scaling exp_id=21pretrainnormal_KG_ftSGev wandb.id=21pretrainnormal_KG_ftSGev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0  zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_KG wandb.id=fno_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_KG wandb.id=deeponet_KG exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_KG_ftSG wandb.id=fno_KG_ftSG exp_name=scaling reload_model=checkpoint/jingmins/dumped/scaling/fno_KG/checkpoint.pth train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_KG_ftSG wandb.id=deeponet_KG_ftSG exp_name=scaling reload_model=checkpoint/jingmins/dumped/scaling/deeponet_KG/checkpoint.pth train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1 batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
#
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/fno_KG/checkpoint.pth exp_name=scaling exp_id=fno_KGev wandb.id=fno_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model=fno data.input_len=2 data.input_step=1  noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/deeponet_KG/checkpoint.pth exp_name=scaling exp_id=deeponet_KGev wandb.id=deeponet_KGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model=deeponet  data.input_len=2 data.input_step=1  noise=0
#
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/fno_KG_ftSG/checkpoint.pth exp_name=scaling exp_id=fno_KG_ftSGev wandb.id=fno_KG_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon] model=fno data.input_len=2 data.input_step=1  noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/deeponet_KG_ftSG/checkpoint.pth exp_name=scaling exp_id=deeponet_KG_ftSGev wandb.id=deeponet_KG_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Klein_Gordon,Sine_Gordon]  model=deeponet data.input_len=2 data.input_step=1  noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain wandb.id=11pretrain exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=${train_type} data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain wandb.id=21pretrain exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=${train_type} data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal wandb.id=21pretrainnormal exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  model.no_text=0  zero_shot_only=1 meta=0 data.train_types=${train_type} data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain_ftSG wandb.id=11pretrain_ftSG reload_model=checkpoint/jingmins/dumped/scaling/11pretrain/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain_ftSG wandb.id=21pretrain_ftSG reload_model=checkpoint/jingmins/dumped/scaling/21pretrain/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal_ftSG wandb.id=21pretrainnormal_ftSG reload_model=checkpoint/jingmins/dumped/scaling/21pretrainnormal/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0  zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain_ftSG20 wandb.id=11pretrain_ftSG20 reload_model=checkpoint/jingmins/dumped/scaling/11pretrain/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 train_size_get=20 eval_size_get=400 zero_shot_only=1  batch_size=20  n_steps_per_epoch=1  max_epoch=100  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain_ftSG20 wandb.id=21pretrain_ftSG20 reload_model=checkpoint/jingmins/dumped/scaling/21pretrain/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 train_size_get=20 eval_size_get=400 zero_shot_only=1  batch_size=20  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal_ftSG20 wandb.id=21pretrainnormal_ftSG20 reload_model=checkpoint/jingmins/dumped/scaling/21pretrainnormal/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 train_size_get=20 eval_size_get=400 zero_shot_only=1  batch_size=20  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0  zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=${eval_type} model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno wandb.id=fno exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${train_type}  data.eval_types=${eval_type} model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet wandb.id=deeponet exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${train_type}  data.eval_types=${eval_type} model=deeponet   data.input_len=2 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_ftSG wandb.id=fno_ftSG reload_model=checkpoint/jingmins/dumped/scaling/fno/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=100 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon]  data.eval_types=[Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_ftSG wandb.id=deeponet_ftSG reload_model=checkpoint/jingmins/dumped/scaling/deeponet/checkpoint.pth exp_name=scaling train_size=4500 eval_size=400 eval_size_get=400 train_size_get=100 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon]  data.eval_types=[Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/fno/checkpoint.pth exp_name=scaling exp_id=fnoev wandb.id=fnoev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 zero_shot_only=1 meta=0 data.eval_types=${eval_type} model=fno data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/deeponet/checkpoint.pth exp_name=scaling exp_id=deeponetev wandb.id=deeponetev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=1 meta=0 data.eval_types=${eval_type}   model=deeponet  data.input_len=2 data.input_step=1  noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain/checkpoint.pth exp_name=scaling exp_id=11pretrainev wandb.id=11pretrainev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0  data.eval_types=${eval_type}  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain/checkpoint.pth exp_name=scaling exp_id=21pretrainev wandb.id=21pretrainev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0  data.eval_types=${eval_type}  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal/checkpoint.pth exp_name=scaling exp_id=21pretrainnormalev wandb.id=21pretrainnormalev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 zero_shot_only=1 meta=0  data.eval_types=${eval_type}  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_ftSG/checkpoint.pth exp_name=scaling exp_id=11pretrain_ftSGev wandb.id=11pretrain_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0  data.eval_types=${eval_type}  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_ftSG/checkpoint.pth exp_name=scaling exp_id=21pretrain_ftSGev wandb.id=21pretrain_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0  data.eval_types=${eval_type}  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal_ftSG/checkpoint.pth exp_name=scaling exp_id=21pretrainnormal_ftSGev wandb.id=21pretrainnormal_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 zero_shot_only=1 meta=0  data.eval_types=${eval_type}  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0



#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_wave wandb.id=fno_wave exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_wave wandb.id=deeponet_wave exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  zero_shot_only=1 meta=0 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_wave_ftSG wandb.id=fno_wave_ftSG exp_name=scaling reload_model=checkpoint/jingmins/dumped/scaling/fno_wave/checkpoint.pth train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[wave,Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_wave_ftSG wandb.id=deeponet_wave_ftSG exp_name=scaling reload_model=checkpoint/jingmins/dumped/scaling/deeponet_wave/checkpoint.pth train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1 batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[wave,Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/fno_wave/checkpoint.pth exp_name=scaling exp_id=fno_waveev wandb.id=fno_waveev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model=fno data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/deeponet_wave/checkpoint.pth exp_name=scaling exp_id=deeponet_waveev wandb.id=deeponet_waveev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model=deeponet  data.input_len=2 data.input_step=1  noise=0
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/fno_wave_ftSG/checkpoint.pth exp_name=scaling exp_id=fno_wave_ftSGev wandb.id=fno_wave_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon] model=fno data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/deeponet_wave_ftSG/checkpoint.pth exp_name=scaling exp_id=deeponet_wave_ftSGev wandb.id=deeponet_wave_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model=deeponet data.input_len=2 data.input_step=1  noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain_wave wandb.id=11pretrain_wave exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain_wave wandb.id=21pretrain_wave exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal_wave wandb.id=21pretrainnormal_wave exp_name=scaling train_size=81000 eval_size=400 eval_size_get=400 train_size_get=81000 batch_size=512  model.no_text=0 zero_shot_only=1 meta=0 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
###
####
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrain_wave_ftSG wandb.id=11pretrain_wave_ftSG reload_model=checkpoint/jingmins/dumped/scaling/11pretrain_wave/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrain_wave_ftSG wandb.id=21pretrain_wave_ftSG reload_model=checkpoint/jingmins/dumped/scaling/21pretrain_wave/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormal_wave_ftSG wandb.id=21pretrainnormal_wave_ftSG reload_model=checkpoint/jingmins/dumped/scaling/21pretrainnormal_wave/checkpoint.pth exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_wave/checkpoint.pth exp_name=scaling exp_id=11pretrain_waveev wandb.id=11pretrain_waveev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_wave/checkpoint.pth exp_name=scaling exp_id=21pretrain_waveev wandb.id=21pretrain_waveev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal_wave/checkpoint.pth exp_name=scaling exp_id=21pretrainnormal_waveev wandb.id=21pretrainnormal_waveev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0  zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_wave_ftSG/checkpoint.pth exp_name=scaling exp_id=11pretrain_wave_ftSGev wandb.id=11pretrain_wave_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_wave_ftSG/checkpoint.pth exp_name=scaling exp_id=21pretrain_wave_ftSGev wandb.id=21pretrain_wave_ftSGev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormal_wave_ftSG/checkpoint.pth exp_name=scaling exp_id=21pretrainnormal_wave_ftSGev wandb.id=21pretrainnormal_wave_ftSGev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0  zero_shot_only=1 meta=0 data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain/checkpoint.pth exp_name=LeMON exp_id=reg_proseev wandb.id=reg_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain/checkpoint.pth exp_name=LeMON exp_id=reg_tproseev wandb.id=reg_tproseev eval_only=true  data.train_types=${train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_KG/checkpoint.pth exp_name=LeMON exp_id=reg_proseKGev wandb.id=reg_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_KG/checkpoint.pth exp_name=LeMON exp_id=reg_tproseKGev wandb.id=reg_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain/checkpoint.pth exp_name=LeMON exp_id=reg_proseev wandb.id=reg_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain/checkpoint.pth exp_name=LeMON exp_id=reg_tproseev wandb.id=reg_tproseev eval_only=true  data.train_types=${train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0 meta_step_eval=20
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_KG/checkpoint.pth exp_name=LeMON exp_id=reg_proseKGev wandb.id=reg_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_KG/checkpoint.pth exp_name=LeMON exp_id=reg_tproseKGev wandb.id=reg_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0 meta_step_eval=20


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_wave/checkpoint.pth exp_name=LeMON exp_id=reg_prosewaveev wandb.id=reg_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrain_wave/checkpoint.pth exp_name=LeMON exp_id=reg_prosewaveev wandb.id=reg_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_wave/checkpoint.pth exp_name=LeMON exp_id=reg_tprosewaveev wandb.id=reg_tprosewaveev eval_only=true  data.train_types=[wave] train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon]  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrain_wave/checkpoint.pth exp_name=LeMON exp_id=reg_tprosewaveev wandb.id=reg_tprosewaveev eval_only=true  data.train_types=[wave] train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon]  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_tprose wandb.id=maml_tprose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tprose/checkpoint.pth exp_name=LeMON exp_id=maml_tproseev wandb.id=maml_tproseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_prose wandb.id=maml_prose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_prose/checkpoint.pth exp_name=LeMON exp_id=maml_proseev wandb.id=maml_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type}  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrainscratch wandb.id=11pretrainscratch  exp_name=scaling train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainscratch wandb.id=21pretrainscratch exp_name=scaling train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormalscratch wandb.id=21pretrainnormalscratch exp_name=scaling train_size=4500 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100 log_periodic=1 model.no_text=0  zero_shot_only=1 meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Sine_Gordon] model.name=prose model.meta.gd_eta=0  data.input_len=2 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fno_scratch wandb.id=fno_scratch exp_name=scaling train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1  batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Sine_Gordon] model=fno   data.input_len=2 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponet_scratch wandb.id=deeponet_scratch exp_name=scaling  train_size=81000 eval_size=400 train_size_get=100 eval_size_get=400 zero_shot_only=1 batch_size=100  n_steps_per_epoch=1  max_epoch=100  meta=0 data.train_types=[Sine_Gordon] data.eval_types=[Sine_Gordon] model=deeponet   data.input_len=2 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/fno_scratch/checkpoint.pth exp_name=scaling exp_id=fno_scratchev wandb.id=fno_scratchev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=1 meta=0 data.eval_types=[Sine_Gordon]  model=fno data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/deeponet_scratch/checkpoint.pth exp_name=scaling exp_id=deeponet_scratchev wandb.id=deeponet_scratchev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000   zero_shot_only=1 meta=0 data.eval_types=[Sine_Gordon]  model=deeponet  data.input_len=2 data.input_step=1  noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/11pretrainscratch/checkpoint.pth exp_name=scaling exp_id=11pretrainscratchev wandb.id=11pretrainscratchev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=1 zero_shot_only=1 meta=0  data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainscratch/checkpoint.pth exp_name=scaling exp_id=21pretrainscratchev wandb.id=21pretrainscratchev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0  data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/scaling/21pretrainnormalscratch/checkpoint.pth exp_name=scaling exp_id=21pretrainnormalscratchev wandb.id=21pretrainnormalscratchev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  model.no_text=0 zero_shot_only=1 meta=0  data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0  model.name=prose data.input_len=2 data.input_step=1  noise=0

#
##
##
##pre_train_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux]
##eval_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux,conservation_randomflux,inviscid_conservation_randomflux]
##eval_data=[one_shock,two_shocks,rarefaction,reg]
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=21shock_cons wandb.id=21shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21shock_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_consev wandb.id=21shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21shock_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_consev wandb.id=21shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=11shock_cons wandb.id=11shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11shock_cons/checkpoint.pth exp_name=LeMON exp_id=11shock_consev wandb.id=11shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11shock_cons/checkpoint.pth exp_name=LeMON exp_id=11shock_consev wandb.id=11shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21shock_cons wandb.id=maml_21shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21shock_cons exp_name=LeMON exp_id=maml_21shock_consev wandb.id=maml_21shock_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21shock_cons exp_name=LeMON exp_id=maml_21shock_consev wandb.id=maml_21shock_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_11shock_cons wandb.id=maml_11shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11shock_cons exp_name=LeMON exp_id=maml_11shock_consev wandb.id=maml_11shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11shock_cons exp_name=LeMON exp_id=maml_11shock_consev wandb.id=maml_11shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
##
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=212shock_cons wandb.id=212shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/212shock_cons/checkpoint.pth exp_name=LeMON exp_id=212shock_consev wandb.id=212shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/212shock_cons/checkpoint.pth exp_name=LeMON exp_id=212shock_consev wandb.id=212shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=112shock_cons wandb.id=112shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/112shock_cons/checkpoint.pth exp_name=LeMON exp_id=112shock_consev wandb.id=112shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/112shock_cons/checkpoint.pth exp_name=LeMON exp_id=112shock_consev wandb.id=112shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21shock_cons wandb.id=maml_21shock_cons1 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 model.meta.meta_lr=0.01
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21shock_cons exp_name=LeMON exp_id=maml_21shock_consev wandb.id=maml_21shock_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21shock_cons exp_name=LeMON exp_id=maml_21shock_consev wandb.id=maml_21shock_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_212shock_cons  wandb.id=maml_212shock_cons1 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 model.meta.meta_lr=0.01
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_212shock_cons exp_name=LeMON exp_id=maml_212shock_consev wandb.id=maml_212shock_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_212shock_cons exp_name=LeMON exp_id=maml_212shock_consev wandb.id=maml_212shock_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_112shock_cons wandb.id=maml_112shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_112shock_cons exp_name=LeMON exp_id=maml_112shock_consev wandb.id=maml_112shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_112shock_cons exp_name=LeMON exp_id=maml_112shock_consev wandb.id=maml_112shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_112shock_cons1 wandb.id=maml_112shock_cons1 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.01
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_112shock_cons1 exp_name=LeMON exp_id=maml_112shock_cons1ev wandb.id=maml_112shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_112shock_cons1 exp_name=LeMON exp_id=maml_112shock_cons1ev wandb.id=maml_112shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=21rare_cons wandb.id=21rare_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21rare_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_consev wandb.id=21shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21rare_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_consev wandb.id=21shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0  meta_step_eval=20
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=11rare_cons wandb.id=11rare_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11rare_cons/checkpoint.pth exp_name=LeMON exp_id=11rare_consev wandb.id=11rare_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11rare_cons/checkpoint.pth exp_name=LeMON exp_id=11rare_consev wandb.id=11rare_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=21_cons wandb.id=21_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21_cons/checkpoint.pth exp_name=LeMON exp_id=21_consev wandb.id=21_consev eval_only=true  data.train_types=${pre_train_type}  data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21_cons/checkpoint.pth exp_name=LeMON exp_id=21_consev wandb.id=21_consev eval_only=true  data.train_types=${pre_train_type}  data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
###
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=11_cons wandb.id=11_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11_cons/checkpoint.pth exp_name=LeMON exp_id=11_consev wandb.id=11_consev eval_only=true  data.train_types=${pre_train_type}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11_cons/checkpoint.pth exp_name=LeMON exp_id=11_consev wandb.id=11_consev eval_only=true  data.train_types=${pre_train_type}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#
###========================
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21fall wandb.id=maml_21fall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1 data.eval_types=-1  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21fall/checkpoint.pth exp_name=LeMON exp_id=maml_21allfev wandb.id=maml_21allfev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21fall/checkpoint.pth exp_name=LeMON exp_id=maml_21allfev wandb.id=maml_21allfev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=LeMON exp_id=maml_fno_all wandb.id=maml_fno_all train_size_get=4500  train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_fno_all/checkpoint.pth exp_name=LeMON exp_id=maml_fno_allev wandb.id=maml_fno_allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=fno data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_fno_all/checkpoint.pth exp_name=LeMON exp_id=maml_fno_allev wandb.id=maml_fno_allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=fno data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=LeMON exp_id=maml_deeponet_all wandb.id=maml_deeponet_all train_size_get=4500  train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
###CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_deeponet_all/checkpoint.pth exp_name=LeMON exp_id=maml_deeponet_allev wandb.id=maml_deeponet_allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_deeponet_all/checkpoint.pth exp_name=LeMON exp_id=maml_deeponet_allev wandb.id=maml_deeponet_allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
