GPU=0

user=aaa
type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]


CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prose_learnlr wandb.id=maml_prose_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt model.meta.meta_lr=0.05
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prose_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_prose_learnlrev wandb.id=maml_prose_learnlrev eval_only=true  data.train_types=${type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True  data.eval_types=${type}  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false  exp_id=maml_fnoall_learnlr wandb.id=maml_fnoall_learnlr exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno  model.meta.learnable_lr=True data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.hidden_channels=128
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_learnlr/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_learnlrev wandb.id=maml_fnoall_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetall_learnlr wandb.id=maml_deeponetall_learnlr exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet model.meta.learnable_lr=True   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.basis_dim=100 model.hidden_dim=256
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_learnlr exp_name=LeMON1 exp_id=maml_deeponetall_learnlrev wandb.id=maml_deeponetall_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256

#### Fixed Learning Rate
lr=0.005
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prose wandb.id=maml_prose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt model.meta.meta_lr=${lr}
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prose/checkpoint.pth exp_name=LeMON1 exp_id=maml_proseev wandb.id=maml_proseev eval_only=true  data.train_types=${type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type}  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=${lr}

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_fno wandb.id=maml_fno ex_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=${lr}
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fno/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnosev wandb.id=maml_fnoev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=${lr}

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponet wandb.id=maml_deeponet exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=${lr}
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponet/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetev wandb.id=maml_deeponetev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=${lr}
