GPU=0
user=jingmins
#pre_train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon]
#eval_type=[diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,Sine_Gordon,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]




#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_deepo_IC wandb.id=maml_pretrain_deepo_IC train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_deepo_IC exp_name=rebuttal exp_id=maml_pretrain_deepoICeval wandb.id=maml_pretrain_deepoICeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_deepo_IC wandb.id=reg_pretrain_deepo_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=-1  model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_deepo_IC exp_name=rebuttal exp_id=reg_pretrain_deepo_IC wandb.id=reg_pretrain_deepo_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_fno_IC wandb.id=maml_pretrain_fno_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_fno_IC exp_name=rebuttal exp_id=maml_pretrain_fno_ICeval wandb.id=maml_pretrain_fnoe_ICval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=-1 model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_fno_IC exp_name=rebuttal exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_IC wandb.id=maml_pretrain_prose_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_IC exp_name=rebuttal exp_id=maml_pretrain_prosee_ICval wandb.id=maml_pretrain_prose_ICeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=-1 model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_prose_IC exp_name=rebuttal exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_wtext_IC wandb.id=maml_pretrain_prose_wtext_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_wtext_IC exp_name=rebuttal exp_id=maml_pretrain_prose_wtexteval_IC wandb.id=maml_pretrain_prose_wtexteval_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_prose_wtext_IC wandb.id=reg_pretrain_prose_wtext_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=-1 model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_prose_wtext_IC exp_name=rebuttal exp_id=reg_pretrain_prose_wtext_IC wandb.id=reg_pretrain_prose_wtext_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_deepo_Step4 wandb.id=reg_pretrain_deepo_Step4 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=-1  model=deeponet  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_deepo_Step4 exp_name=rebuttal exp_id=reg_pretrain_deepo_Step4 wandb.id=reg_pretrain_deepo_Step4 eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_fno_Step4 wandb.id=maml_pretrain_fno_Step4 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_fno_Step4 exp_name=rebuttal exp_id=maml_pretrain_fno_Step4eval wandb.id=maml_pretrain_fnoe_Step4val eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_fno_Step4 wandb.id=reg_pretrain_fno_Step4 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=-1 model=fno  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_fno_Step4 exp_name=rebuttal exp_id=reg_pretrain_fno_Step4 wandb.id=reg_pretrain_fno_Step4 eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_Step4 wandb.id=maml_pretrain_prose_Step4 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_Step4 exp_name=rebuttal exp_id=maml_pretrain_prosee_Step4val wandb.id=maml_pretrain_prose_Step4eval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_prose_Step4 wandb.id=reg_pretrain_prose_Step4 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=-1 model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_prose_Step4 exp_name=rebuttal exp_id=reg_pretrain_prose_Step4 wandb.id=reg_pretrain_prose_Step4 eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_wtext_Step4 wandb.id=maml_pretrain_prose_wtext_Step4 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_wtext_Step4 exp_name=rebuttal exp_id=maml_pretrain_prose_wtexteval_Step4 wandb.id=maml_pretrain_prose_wtexteval_Step4 eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_prose_wtext_Step4 wandb.id=reg_pretrain_prose_wtext_Step4 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=-1 model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=4 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_prose_wtext_Step4 exp_name=rebuttal exp_id=reg_pretrain_prose_wtext_Step4 wandb.id=reg_pretrain_prose_wtext_Step4 eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=4 data.input_step=1 noise=0

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_deepol_largerbs_IC wandb.id=maml_pretrain_deepol_largerbs_IC train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_deepol_largerbs_IC exp_name=rebuttal exp_id=maml_pretrain_deepol_largerbs_ICeval wandb.id=maml_pretrain_deepoeval_largerbs_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_deepol_IC wandb.id=reg_pretrain_deepol_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=-1  model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_deepol_IC exp_name=rebuttal exp_id=reg_pretrain_deepol_IC wandb.id=reg_pretrain_deepol_IC_eval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_fno_largerbs_IC wandb.id=maml_pretrain_fno_largerbs_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_fno_largerbs_IC2 exp_name=rebuttal exp_id=maml_pretrain_fno_largerbs_ICeval wandb.id=maml_pretrain_deepoeval_largerbs_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC3 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=-1  model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_fno_IC3 exp_name=rebuttal exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC_eval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


types=[burgers,conservation_linearflux,conservation_sinflux,conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,inviscid_conservation_cubicflux,advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,diff_squarelogisticreact_1D,cahnhilliard_1D,Sine_Gordon,kdv,diff_logisreact_1D,wave,porous_medium]

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=prose exp_id=fno wandb.id=fno train_size_get=-1 train_size=25600 eval_size=5120 eval_size_get=-1  data.train_types=${types}  data.eval_types=${types}  model=fno  batch_size=512 max_epoch=30 zero_shot_only=1  data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/fno exp_name=prose exp_id=fno_ev wandb.id=fno_ev eval_only=true  data.train_types=${types} train_size=30720  eval_size=5120 eval_size_get=-1 meta=0 model=fno data.train_types=${types} data.eval_types=${types} zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/fno exp_name=prose exp_id=fnoood_ev wandb.id=fnoood_ev eval_only=true  data.train_types=${types} train_size=0  eval_size=5120 eval_size_get=-1 meta=0 model=fno data.train_types=${types} data.eval_types=${types} data.eval_data=[ood0.80.9,00d1.11.2] zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/fno exp_name=prose exp_id=fnoinputclass_ev wandb.id=fnoinputclass_ev eval_only=true  data.train_types=${types} train_size=30720  eval_size=5120 eval_size_get=-1 meta=0 model=fno data.train_types=${types} data.eval_types=${types} data.eval_data=ICextr zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=prose exp_id=deeponet wandb.id=deeponet train_size_get=-1 train_size=25600 eval_size=5120 eval_size_get=-1  data.train_types=${types}  data.eval_types=${types} model=deeponet  batch_size=512 max_epoch=30 zero_shot_only=1  data.input_len=1 data.input_step=1 meta=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/deeponet exp_name=prose exp_id=deeponetev wandb.id=deeponetev eval_only=true   data.train_types=${types} train_size=30720  eval_size=5120 eval_size_get=-1   meta=0  model=deeponet data.train_types=${types} data.eval_types=${types} zero_shot_only=1  data.input_len=1 data.input_step=1 noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/deeponet exp_name=prose exp_id=deeponetoodev wandb.id=deeponetoodev eval_only=true   data.train_types=${types} train_size=0  eval_size=5120 eval_size_get=-1   meta=0  model=deeponet data.train_types=${types} data.eval_types=${types} data.eval_data=[ood0.80.9,00d1.11.2] zero_shot_only=1  data.input_len=1 data.input_step=1 noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/deeponet exp_name=prose exp_id=deeponetinputclassev wandb.id=deeponetinputclassev eval_only=true   data.train_types=${types} train_size=30720  eval_size=5120 eval_size_get=-1   meta=0  model=deeponet data.train_types=${types} data.eval_types=${types} data.eval_data=ICextr  zero_shot_only=1  data.input_len=1 data.input_step=1 noise=0