GPU=1
user=jingmins
pre_train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon]
eval_type=[diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,Sine_Gordon,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=deeponet exp_id=maml_pretrain wandb.id=maml_pretrain train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/deeponet/maml_pretrain exp_name=deeponet exp_id=maml_pretraineval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=fno exp_id=maml_pretrain wandb.id=maml_pretrain train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/fno/maml_pretrain exp_name=deeponet exp_id=maml_pretraineval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=prose exp_id=maml_pretrain wandb.id=maml_pretrain train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/prose/maml_pretrain exp_name=deeponet exp_id=maml_pretraineval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=prose exp_id=maml_pretrain_wtext wandb.id=maml_pretrain_wtext train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/prose/maml_pretrain_wtext exp_name=deeponet exp_id=maml_pretrain_wtexteval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
