GPU=0
user=jingmins
pre_train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon]
eval_type=[diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,Sine_Gordon,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=deeponet exp_id=maml_pretrain wandb.id=maml_pretrain train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/deeponet/maml_pretrain exp_name=deeponet exp_id=maml_pretraineval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=fno exp_id=maml_pretrain wandb.id=maml_pretrain train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/fno/maml_pretrain exp_name=deeponet exp_id=maml_pretraineval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=prose exp_id=maml_pretrain wandb.id=maml_pretrain train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/prose/maml_pretrain exp_name=deeponet exp_id=maml_pretraineval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=prose exp_id=maml_pretrain_wtext wandb.id=maml_pretrain_wtext train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.train_data=onlyqc data.eval_data=onlyqc data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256  eval_from_exp=checkpoint/${user}/dumped/prose/maml_pretrain_wtext exp_name=deeponet exp_id=maml_pretrain_wtexteval wandb.id=maml_pretraineval eval_only=true data.eval_data=onlyqc data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=10000 eval_size_get=10000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0




#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_deepo wandb.id=maml_pretrain_deepo train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_deepo exp_name=rebuttal exp_id=maml_pretrain_deepoeval wandb.id=maml_pretrain_deepoeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_fno wandb.id=maml_pretrain_fno train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_fno exp_name=rebuttal exp_id=maml_pretrain_fnoeval wandb.id=maml_pretrain_fnoeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose wandb.id=maml_pretrain_prose train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose exp_name=rebuttal exp_id=maml_pretrain_proseeval wandb.id=maml_pretrain_proseeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_wtext wandb.id=maml_pretrain_prose_wtext train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_wtext exp_name=rebuttal exp_id=maml_pretrain_prose_wtexteval wandb.id=maml_pretrain_prose_wtexteval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_deepo wandb.id=reg_pretrain_deepo train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=-1  model=deeponet  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_deepo exp_name=rebuttal exp_id=reg_pretrain_deepo wandb.id=reg_pretrain_deepo eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_fno wandb.id=reg_pretrain_fno train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=-1 model=fno  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_fno exp_name=rebuttal exp_id=reg_pretrain_fno wandb.id=reg_pretrain_fno eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_prose wandb.id=reg_pretrain_prose train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=-1 model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_prose exp_name=rebuttal exp_id=reg_pretrain_prose wandb.id=reg_pretrain_prose eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=reg_pretrain_prose_wtext wandb.id=reg_pretrain_prose_wtext train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=-1 model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/reg_pretrain_prose_wtext exp_name=rebuttal exp_id=reg_pretrain_prose_wtext wandb.id=reg_pretrain_prose_wtext eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0




#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_deepo_largerbs wandb.id=maml_pretrain_deepo_largerbs train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_deepo_largerbs exp_name=rebuttal exp_id=maml_pretrain_deepo_largerbseval wandb.id=maml_pretrain_deepoeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_fno wandb.id=maml_pretrain_fno train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_fno exp_name=rebuttal exp_id=maml_pretrain_fnoeval wandb.id=maml_pretrain_fnoeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_largerbs wandb.id=maml_pretrain_prose_largerbs train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_largerbs exp_name=rebuttal exp_id=maml_pretrain_prose_largerbseval wandb.id=maml_pretrain_proseeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_wtext_largerbs wandb.id=maml_pretrain_prose_wtext_largerbs train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_wtext_largerbs exp_name=rebuttal exp_id=maml_pretrain_prose_wtext_largerbseval wandb.id=maml_pretrain_prose_wtexteval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_deepo_largerbs_IC wandb.id=maml_pretrain_deepo_largerbs_IC train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_deepo_largerbs_IC exp_name=rebuttal exp_id=maml_pretrain_deepo_largerbseval_IC wandb.id=maml_pretrain_deepoeval_largerbs_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_largerbs_IC wandb.id=maml_pretrain_prose_largerbs_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_largerbs_IC exp_name=rebuttal exp_id=maml_pretrain_prose_largerbseval_IC wandb.id=maml_pretrain_proseeval_largerbs_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal exp_id=maml_pretrain_prose_wtext_largerbs_IC wandb.id=maml_pretrain_prose_wtext_largerbs_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal/maml_pretrain_prose_wtext_largerbs_IC exp_name=rebuttal exp_id=maml_pretrain_prose_wtext_largerbseval_IC wandb.id=maml_pretrain_prose_wtexteval_largerbs_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose data.train_types=${eval_type} data.eval_types=-1 zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0

types=[burgers,conservation_linearflux,conservation_sinflux,conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,inviscid_conservation_cubicflux,advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,diff_squarelogisticreact_1D,cahnhilliard_1D,Sine_Gordon,kdv,diff_logisreact_1D,wave,porous_medium]
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/fno exp_name=prose exp_id=fno_ev wandb.id=fno_ev eval_only=true  data.train_types=${types} train_size=30720  eval_size=5120 eval_size_get=-1 meta=0 model=fno data.train_types=${types} data.eval_types=${types} zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/fno exp_name=prose exp_id=fnoood_ev wandb.id=fnoood_ev eval_only=true  data.train_types=${types} train_size=0  eval_size=5120 eval_size_get=-1 meta=0 model=fno data.train_types=${types} data.eval_types=${types} data.eval_data=[ood0.80.9,00d1.11.2] zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 eval_from_exp=checkpoint/${user}/dumped/prose/fno exp_name=prose exp_id=fnoinputclass_ev wandb.id=fnoinputclass_ev eval_only=true  data.train_types=${types} train_size=30720  eval_size=5120 eval_size_get=-1 meta=0 model=fno data.train_types=${types} data.eval_types=${types} data.eval_data=ICextr zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0
