GPU=1
user=jingmins
#pre_train_type=[conservation_sinflux,conservation_cubicflux,conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux]
#eval_type=[conservation_sinflux,conservation_cubicflux,conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,burgers]
#
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_deepo_IC wandb.id=maml_pretrain_deepo_IC train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_deepo_IC exp_name=rebuttal_cons exp_id=maml_pretrain_deepoICeval wandb.id=maml_pretrain_deepoICeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=deeponet data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_deepo_IC wandb.id=reg_pretrain_deepo_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=${eval_type}  model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_deepo_IC exp_name=rebuttal_cons exp_id=reg_pretrain_deepo_IC wandb.id=reg_pretrain_deepo_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_fno_IC wandb.id=maml_pretrain_fno_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_fno_IC exp_name=rebuttal_cons exp_id=maml_pretrain_fno_ICeval wandb.id=maml_pretrain_fnoe_ICval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=${eval_type} model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_fno_IC exp_name=rebuttal_cons exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_prose_IC wandb.id=maml_pretrain_prose_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_prose_IC exp_name=rebuttal_cons exp_id=maml_pretrain_prosee_ICval wandb.id=maml_pretrain_prose_ICeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_prose_IC exp_name=rebuttal_cons exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_prose_wtext_IC wandb.id=maml_pretrain_prose_wtext_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_prose_wtext_IC exp_name=rebuttal_cons exp_id=maml_pretrain_prose_wtexteval_IC wandb.id=maml_pretrain_prose_wtexteval_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_prose_wtext_IC wandb.id=reg_pretrain_prose_wtext_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_prose_wtext_IC exp_name=rebuttal_cons exp_id=reg_pretrain_prose_wtext_IC wandb.id=reg_pretrain_prose_wtext_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0

#
#pre_train_type=[conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,diff_linearreact_1D,diff_logisreact_1D]
#eval_type=[conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,diff_linearreact_1D,diff_logisreact_1D,conservation_sinflux,inviscid_conservation_cubicflux,burgers,diff_bistablereact_1D,diff_squarelogisticreact_1D]
#
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_deepo_IC wandb.id=maml_pretrain_deepo_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_deepo_IC exp_name=rebuttal_cons exp_id=maml_pretrain_deepoICeval wandb.id=maml_pretrain_deepoICeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=deeponet data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_deepo_IC wandb.id=regu_pretrain_deepo_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=${eval_type}  model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_deepo_IC exp_name=rebuttal_cons exp_id=reg_pretrain_deepo_IC wandb.id=reg_pretrain_deepo_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_fno_IC wandb.id=maml_pretrain_fno_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_fno_IC exp_name=rebuttal_cons exp_id=maml_pretrain_fno_ICeval wandb.id=maml_pretrain_fnoe_ICval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=${eval_type} model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_fno_IC exp_name=rebuttal_cons exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_prose_IC wandb.id=maml_pretrain_prose_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_prose_IC exp_name=rebuttal_cons exp_id=maml_pretrain_prosee_ICval wandb.id=maml_pretrain_prose_ICeval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_prose_IC exp_name=rebuttal_cons exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_prose_wtext_IC wandb.id=maml_pretrain_prose_wtext_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_prose_wtext_IC exp_name=rebuttal_cons exp_id=maml_pretrain_prose_wtexteval_IC wandb.id=maml_pretrain_prose_wtexteval_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=reg_pretrain_prose_wtext_IC wandb.id=reg_pretrain_prose_wtext_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=2 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/reg_pretrain_prose_wtext_IC exp_name=rebuttal_cons exp_id=reg_pretrain_prose_wtext_IC_eval wandb.id=reg_pretrain_prose_wtext_IC_eval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=2 data.input_step=1 noise=0


pre_train_type=[advection,diff_bistablereact_1D,heat,inviscid_conservation_cubicflux,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,conservation_cubicflux,diff_logisreact_1D,Sine_Gordon]
eval_type=[advection,diff_bistablereact_1D,heat,inviscid_conservation_cubicflux,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,conservation_cubicflux,diff_logisreact_1D,inviscid_conservation_sinflux,conservation_sinflux,Sine_Gordon,kdv,cahnhilliard_1D,Klein_Gordon,wave,fplanck,porous_medium]



#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC exp_name=diff_sep exp_id=reg_pretrain_prose_IC wandb.id=reg_pretrain_prose_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC wandb.id=reg_pretrain_prose_wtext_IC2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_eval wandb.id=reg_pretrain_prose_wtext_IC_eval eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=diff_sep exp_id=reg_pretrain_deepo_IC wandb.id=regu_pretrain_deepo_IC2 train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=${eval_type}  model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_deepo_IC exp_name=diff_sep exp_id=reg_pretrain_deepo_IC wandb.id=reg_pretrain_deepo_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000  model=deeponet  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400  data.train_types=${pre_train_type}  data.eval_types=${eval_type} model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_fno_IC exp_name=diff_sep exp_id=reg_pretrain_fno_IC wandb.id=reg_pretrain_fno_IC eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model=fno  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_wtext_IC_largerbs wandb.id=maml_pretrain_prose_wtext_IC_largerbs train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_wtext_IC_largerbs exp_name=diff_sep exp_id=maml_pretrain_prose_wtexteval_IC_largerbs wandb.id=maml_pretrain_prose_wtexteval_IC_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinnerSG wandb.id=maml_pretrain_prose_freezetext_IC_largerbs_newinnerSG2 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 base_seed=10011 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinnerSG exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_evalSG wandb.id=maml_pretrain_prose_ICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_IC_largerbs_newinnerSG wandb.id=maml_pretrain_prose_IC_largerbs_newinnerSG train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinnerSG exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=maml_pretrain_prose_ICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_wtext_IC_largerbs_newinnerSG wandb.id=maml_pretrain_prose_wtext_IC_largerbs_newinnerSG train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_wtext_IC_largerbs_newinnerSG exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner_evalSG wandb.id=maml_pretrain_prose_ICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
