GPU=0
user=jingmins


#pre_train_type=[conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,diff_linearreact_1D,diff_logisreact_1D]
#eval_type=[conservation_cubicflux,inviscid_burgers,inviscid_conservation_sinflux,diff_linearreact_1D,diff_logisreact_1D,conservation_sinflux,inviscid_conservation_cubicflux,burgers,diff_bistablereact_1D,diff_squarelogisticreact_1D]
#
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_deepo_IC_largerbs wandb.id=maml_pretrain_deepo_IC_largerbs train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_deepo_IC_largerbs exp_name=rebuttal_cons exp_id=maml_pretrain_deepoICeval_largerbs wandb.id=maml_pretrain_deepoICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_prose_IC_largerbs wandb.id=maml_pretrain_prose_IC_largerbs train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_prose_IC_largerbs exp_name=rebuttal_cons exp_id=maml_pretrain_prosee_ICval_largerbs wandb.id=maml_pretrain_prose_ICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=rebuttal_cons exp_id=maml_pretrain_prose_wtext_IC_largerbs wandb.id=maml_pretrain_prose_wtext_IC_largerbs train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/rebuttal_cons/maml_pretrain_prose_wtext_IC_largerbs exp_name=rebuttal_cons exp_id=maml_pretrain_prose_wtexteval_IC_largerbs wandb.id=maml_pretrain_prose_wtexteval_IC_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_deepo_IC_largerbs wandb.id=maml_pretrain_deepo_IC_largerbs train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_deepo_IC_largerbs exp_name=diff_sep exp_id=maml_pretrain_deepoICeval_largerbs wandb.id=maml_pretrain_deepoICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_IC_largerbs_newinner wandb.id=maml_pretrain_prose_IC_largerbs_newinner train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=maml_pretrain_prose_ICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_wtext_IC_largerbs wandb.id=maml_pretrain_prose_wtext_IC_largerbs train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false  eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_wtext_IC_largerbs exp_name=diff_sep exp_id=maml_pretrain_prose_wtexteval_IC_largerbs wandb.id=maml_pretrain_prose_wtexteval_IC_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=400 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_deepo_IC_largerbs wandb.id=maml_pretrain_deepo_IC_largerbs train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_deepo_IC_largerbs exp_name=diff_sep exp_id=maml_pretrain_deepoICeval_largerbs wandb.id=maml_pretrain_deepoICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_fno_IC_largerbs wandb.id=maml_pretrain_fno_IC_largerbs train_size_get=1000  train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_fno_IC_largerbs exp_name=diff_sep exp_id=maml_pretrain_fnoICeval_largerbs wandb.id=maml_pretrain_deepoICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1000 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=fno data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=maml_pretrain_prose_wtext_IC_largerbs_newinner train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner_eval wandb.id=maml_pretrain_prose_ICeval_largerbs eval_only=true  data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


#
#pre_train_type=[advection,diff_bistablereact_1D,heat,inviscid_conservation_cubicflux,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,conservation_cubicflux,diff_logisreact_1D]
#eval_type=[advection,diff_bistablereact_1D,heat,inviscid_conservation_cubicflux,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,conservation_cubicflux,diff_logisreact_1D,Klein_Gordon,inviscid_conservation_sinflux,conservation_sinflux,kdv,cahnhilliard_1D,Sine_Gordon,wave,fplanck,porous_medium]
#
#
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner wandb.id=maml_pretrain_prose_freezetext_IC_largerbs_newinner train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 base_seed=10011 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_eval wandb.id=ev_maml_prose_freezesymbol eval_only=true  meta_step=5 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_eval wandb.id=ev_maml_prose_freezesymbol eval_only=true  meta_step=10 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_eval wandb.id=ev_maml_prose_freezesymbol eval_only=true  meta_step=15 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_eval wandb.id=ev_maml_prose_freezesymbol eval_only=true  meta_step=20 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_eval wandb.id=ev_maml_prose_freezesymbol eval_only=true  meta_step=25 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_freezetext_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prose_freezetext_IC_largerbs_newinner_eval wandb.id=ev_maml_prose_freezesymbol eval_only=true  meta_step=30 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner wandb.id=reg_pretrain_prose_IC_newinner train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner_eval wandb.id=ev_reg_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=5 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner_eval wandb.id=ev_reg_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=10 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner_eval wandb.id=ev_reg_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=15 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner_eval wandb.id=ev_reg_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=20 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner_eval wandb.id=ev_reg_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=25 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_IC_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_IC_newinner_eval wandb.id=ev_reg_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=30 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner_newev wandb.id=reg_pretrain_prose_wtext_IC_largerbs_newinner_newev3 train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30 model.fusion.n_layer=1 evalfreezedmodule=[symbol_encoder]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=ev_reg_prose_text eval_only=true meta_step=5 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=[symbol_encoder]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=ev_reg_prose_text eval_only=true meta_step=10 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=[symbol_encoder]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=ev_reg_prose_text eval_only=true meta_step=15 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=[symbol_encoder]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=ev_reg_prose_text eval_only=true meta_step=20 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=[symbol_encoder]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=ev_reg_prose_text eval_only=true meta_step=25 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=[symbol_encoder]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/reg_pretrain_prose_wtext_IC_largerbs_newinner exp_name=diff_sep exp_id=reg_pretrain_prose_wtext_IC_largerbs_newinner wandb.id=ev_reg_prose_text eval_only=true meta_step=30 data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=[symbol_encoder]
#
##
##
##CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=diff_sep exp_id=maml_pretrain_prose_IC_largerbs_newinner wandb.id=maml_pretrain_prose_IC_largerbs_newinner train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=ev_maml_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=5 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=ev_maml_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=10 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=ev_maml_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=15 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=ev_maml_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=20 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=ev_maml_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=25 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/diff_sep/maml_pretrain_prose_IC_largerbs_newinner exp_name=diff_sep exp_id=maml_pretrain_prosee_ICval_largerbs_newinner wandb.id=ev_maml_prose eval_only=true  data.train_types=${pre_train_type}  meta_step=30 train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#pre_train_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux]
#eval_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux,conservation_randomflux,inviscid_conservation_randomflux]
#eval_data=[one_shock,two_shocks,rarefaction,reg]
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=maml_prose_tfreeze wandb.id=maml_prose_tfreeze train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_types=${eval_type} data.eval_data=${eval_data} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/maml_prose_tfreeze exp_name=conservation exp_id=maml_prose_tfreezeev wandb.id=maml_prose_tfreezeev eval_only=true  data.train_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} data.eval_data=${eval_data} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0



pre_train_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux]
eval_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux,conservation_randomflux,inviscid_conservation_randomflux]
eval_data=[one_shock,two_shocks,rarefaction,reg]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=reg_tprose_shock wandb.id=reg_tprose_shock train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30 model.fusion.n_layer=1 evalfreezedmodule=["symbol_encoder"]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_tprose_shock exp_name=conservation exp_id=reg_tprose_shockev wandb.id=reg_tprose_shockev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=["symbol_encoder"]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_prose exp_name=conservation exp_id=reg_proseev wandb.id=reg_proseev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=1 model.name=prose   zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_tprose exp_name=conservation exp_id=reg_tproseev wandb.id=reg_tproseev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=["symbol_encoder"]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/maml_prose exp_name=conservation exp_id=maml_proseev wandb.id=maml_proseev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose   zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/maml_prose_tfreeze exp_name=conservation exp_id=maml_prose_tfreezeev wandb.id=maml_prose_tfreezeev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_prose_regft exp_name=conservation exp_id=reg_prose_regftev wandb.id=reg_prose_regftev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=1 model.name=prose   zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_tprose_regftfreezet exp_name=conservation exp_id=reg_tprose_regftfreezetev wandb.id=reg_tprose_regftfreezetev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 evalfreezedmodule=["symbol_encoder"]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_prose_mamlft exp_name=conservation exp_id=reg_prose_mamlftev wandb.id=reg_prose_mamlftev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose   zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_tprose_mamlftfreezet exp_name=conservation exp_id=reg_tprose_mamlftfreezetev wandb.id=reg_tprose_mamlftfreezetev eval_only=true  data.train_types=${pre_train_type} data.eval_types=${eval_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=maml_prose_tfreeze_shock wandb.id=maml_prose_tfreeze_shock train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/maml_prose_tfreeze_shock exp_name=conservation exp_id=maml_prose_tfreeze_shockev wandb.id=maml_prose_tfreeze_shockev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=reg_tprose_mamlftfreezetalways wandb.id=reg_tprose_mamlftfreezetalways reload_model=checkpoint/${user}/dumped/conservation/reg_tprose/checkpoint.pth train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type}  model.fusion.n_layer=1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose freezedmodule=["symbol_encoder"]  model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=maml_prose_regft wandb.id=maml_prose_regft  reload_model=checkpoint/${user}/dumped/conservation/maml_prose/checkpoint.pth  train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type}  model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=maml_prose_mamlft wandb.id=maml_prose_mamlft reload_model=checkpoint/${user}/dumped/conservation/maml_prose/checkpoint.pth train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type}   model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=reg_tprose_mamlftfreezetalways wandb.id=reg_tprose_mamlftfreezetalways base_seed=10011 reload_model=checkpoint/${user}/dumped/conservation/reg_tprose/checkpoint.pth train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type}  model.fusion.n_layer=1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose freezedmodule=["symbol_encoder"]  model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=maml_tprose_mamlftfreezetalways wandb.id=maml_tprose_mamlftfreezetalways reload_model=checkpoint/${user}/dumped/conservation/maml_prose_tfreeze/checkpoint.pth train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type}  model.fusion.n_layer=1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose freezedmodule=["symbol_encoder"]  model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=30
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=conservation exp_id=reg_tprose_regft wandb.id=reg_tprose_regft  reload_model=checkpoint/${user}/dumped/conservation/reg_tprose/checkpoint.pth  train_size_get=1000 train_size=1000 eval_size=400 eval_size_get=400 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux]  data.eval_types=${eval_type} model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 model.fusion.n_layer=1 max_epoch=30

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_tprose_mamlftfreezetalways exp_name=conservation exp_id=reg_tprose_mamlftfreezetalwaysev wandb.id=reg_tprose_mamlftfreezetalwaysev eval_only=true   train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type} model.fusion.n_layer=1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose freezedmodule=["symbol_encoder"]  model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/maml_tprose_mamlftfreezetalways exp_name=conservation exp_id=maml_tprose_mamlftfreezetalwaysev wandb.id=maml_tprose_mamlftfreezetalwaysev eval_only=true   train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type} model.fusion.n_layer=1 model.meta.gd_eta=0 model.meta.name=MAML model.name=prose freezedmodule=["symbol_encoder"]  model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 noise=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/conservation/reg_tprose_regft exp_name=conservation exp_id=reg_tprose_regftev wandb.id=reg_tprose_regftev eval_only=true   train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 data.train_types=[conservation_randomflux,inviscid_conservation_randomflux] data.eval_types=${eval_type} model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 model.fusion.n_layer=1 evalfreezedmodule=["symbol_encoder"] noise=0
