GPU=1

user=jingmins
#train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]
#eval_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_tproseKG wandb.id=maml_tproseKG train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tproseKG/checkpoint.pth exp_name=LeMON exp_id=maml_tproseKGev wandb.id=maml_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tproseKG/checkpoint.pth exp_name=LeMON exp_id=maml_tproseKGev wandb.id=maml_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_proseKG wandb.id=maml_proseKG train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_proseKG/checkpoint.pth exp_name=LeMON exp_id=maml_proseKGev wandb.id=maml_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_proseKG/checkpoint.pth exp_name=LeMON exp_id=maml_proseKGev wandb.id=maml_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_tprose wandb.id=maml_tprose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tprose/checkpoint.pth exp_name=LeMON exp_id=maml_tproseev wandb.id=maml_tproseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tprose/checkpoint.pth exp_name=LeMON exp_id=maml_tproseev wandb.id=maml_tproseev eval_only=true  train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_prose wandb.id=maml_prose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_prose/checkpoint.pth exp_name=LeMON exp_id=maml_proseev wandb.id=maml_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type}  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_prose/checkpoint.pth exp_name=LeMON exp_id=maml_proseev wandb.id=maml_proseev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_tprosewave wandb.id=maml_tprosewave train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tprosewave/checkpoint.pth exp_name=LeMON exp_id=maml_tprosewaveev wandb.id=maml_tprosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_tprosewave/checkpoint.pth exp_name=LeMON exp_id=maml_tprosewaveev wandb.id=maml_tprosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_prosewave wandb.id=maml_prosewave train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_prosewave/checkpoint.pth exp_name=LeMON exp_id=maml_prosewaveev wandb.id=maml_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_prosewave/checkpoint.pth exp_name=LeMON exp_id=maml_prosewaveev wandb.id=maml_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20


#pre_train_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux]
#eval_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux,conservation_randomflux,inviscid_conservation_randomflux]
#eval_data=[one_shock,two_shocks,rarefaction,reg]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=21rare_cons wandb.id=21rare_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21rare_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_consev wandb.id=21shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21rare_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_consev wandb.id=21shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0  meta_step_eval=10
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=11rare_cons wandb.id=11rare_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11rare_cons/checkpoint.pth exp_name=LeMON exp_id=11rare_consev wandb.id=11rare_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11rare_cons/checkpoint.pth exp_name=LeMON exp_id=11rare_consev wandb.id=11rare_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21rare_cons wandb.id=maml_21rare_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21rare_cons exp_name=LeMON exp_id=maml_21rare_consev wandb.id=maml_21rare_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21rare_cons exp_name=LeMON exp_id=maml_21rare_consev wandb.id=maml_21rare_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_11rare_cons wandb.id=maml_11rare_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11rare_cons exp_name=LeMON exp_id=maml_11rare_consev wandb.id=maml_11rare_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11rare_cons exp_name=LeMON exp_id=maml_11rare_consev wandb.id=maml_11rare_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=rarefaction data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=21_cons wandb.id=21_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21_cons/checkpoint.pth exp_name=LeMON exp_id=21_consev wandb.id=21_consev eval_only=true  data.train_types=${pre_train_type}  data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21_cons/checkpoint.pth exp_name=LeMON exp_id=21_consev wandb.id=21_consev eval_only=true  data.train_types=${pre_train_type}  data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=11_cons wandb.id=11_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 data.train_types=${pre_train_type}  data.eval_types=${eval_type} model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11_cons/checkpoint.pth exp_name=LeMON exp_id=11_consev wandb.id=11_consev eval_only=true  data.train_types=${pre_train_type}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11_cons/checkpoint.pth exp_name=LeMON exp_id=11_consev wandb.id=11_consev eval_only=true  data.train_types=${pre_train_type}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21_cons wandb.id=maml_21_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}   data.eval_types=${eval_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21_cons exp_name=LeMON exp_id=maml_21_consev wandb.id=maml_21_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21_cons exp_name=LeMON exp_id=maml_21_consev wandb.id=maml_21_consev eval_only=true data.train_types=${pre_train_type} data.eval_data=${eval_data}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose   model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_11_cons wandb.id=maml_11_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11_cons exp_name=LeMON exp_id=maml_11_consev wandb.id=maml_11_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}   data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11_cons exp_name=LeMON exp_id=maml_11_consev wandb.id=maml_11_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.eval_types=${eval_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_11shock_cons1 wandb.id=maml_11shock_cons1 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11shock_cons1 exp_name=LeMON exp_id=maml_11shock_cons1ev wandb.id=maml_11shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11shock_cons1 exp_name=LeMON exp_id=maml_11shock_cons1ev wandb.id=maml_11shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_112shock_cons wandb.id=maml_112shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_112shock_cons exp_name=LeMON exp_id=maml_112shock_consev wandb.id=maml_112shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_112shock_cons exp_name=LeMON exp_id=maml_112shock_consev wandb.id=maml_112shock_consev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=11pretrainall wandb.id=11pretrainall exp_name=LeMON train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  model.no_text=1 zero_shot_only=1 meta=0 data.train_types=-1 data.eval_types=-1 model.name=prose model.meta.gd_eta=0  data.input_len=1 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainall wandb.id=21pretrainall exp_name=LeMON train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  model.no_text=0 model.fusion.n_layer=1 zero_shot_only=1 meta=0 data.train_types=-1 data.eval_types=-1 model.name=prose model.meta.gd_eta=0  data.input_len=1 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=21pretrainnormalall wandb.id=21pretrainnormalall exp_name=LeMON train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  model.no_text=0  zero_shot_only=1 meta=0 data.train_types=-1 data.eval_types=-1 model.name=prose model.meta.gd_eta=0  data.input_len=1 data.input_step=1
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fnoall wandb.id=fnoall exp_name=LeMON train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=-1  data.eval_types=-1 model=fno   data.input_len=1 data.input_step=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponetall wandb.id=deeponetall exp_name=LeMON train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=-1  data.eval_types=-1 model=deeponet   data.input_len=1 data.input_step=1
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11pretrainall/checkpoint.pth exp_name=LeMON exp_id=11pretrainallev wandb.id=11pretrainallev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21pretrainall/checkpoint.pth exp_name=LeMON exp_id=21pretrainallfev wandb.id=21pretrainallfev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21pretrainnormalall/checkpoint.pth exp_name=LeMON exp_id=21pretrainnormalallev wandb.id=21pretrainnormalallev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11pretrainall/checkpoint.pth exp_name=LeMON exp_id=11pretrainallev wandb.id=11pretrainallev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21pretrainall/checkpoint.pth exp_name=LeMON exp_id=21pretrainallfev wandb.id=21pretrainallfev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21pretrainnormalall/checkpoint.pth exp_name=LeMON exp_id=21pretrainnormalallev wandb.id=21pretrainnormalallev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21pretrainall/checkpoint.pth exp_name=LeMON exp_id=21pretrainallev wandb.id=21pretrainallev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/fnoall/checkpoint.pth exp_name=LeMON exp_id=fnoallev wandb.id=fnoallev eval_only=true   train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 zero_shot_only=0 meta=1 data.eval_types=-1 model=fno data.input_len=1 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/deeponetall/checkpoint.pth exp_name=LeMON exp_id=deeponetallev wandb.id=deeponetallev eval_only=true  train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=0 meta=1 data.eval_types=-1   model=deeponet  data.input_len=1 data.input_step=1  noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/fnoall/checkpoint.pth exp_name=LeMON exp_id=fnoallev wandb.id=fnoallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 zero_shot_only=0 meta=1 data.eval_types=-1 model=fno data.input_len=1 data.input_step=1  noise=0 meta_step_eval=10
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/deeponetall/checkpoint.pth exp_name=LeMON exp_id=deeponetallev wandb.id=deeponetallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000  zero_shot_only=0 meta=1 data.eval_types=-1   model=deeponet  data.input_len=1 data.input_step=1  noise=0 meta_step_eval=10




#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21all wandb.id=maml_21all train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1 data.eval_types=-1  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21all/checkpoint.pth exp_name=LeMON exp_id=maml_21allev wandb.id=maml_21allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21all/checkpoint.pth exp_name=LeMON exp_id=maml_21allev wandb.id=maml_21allev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_11all wandb.id=maml_11all train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1 data.eval_types=-1  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11all/checkpoint.pth exp_name=LeMON exp_id=maml_11allev wandb.id=maml_11allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=-1  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_11all/checkpoint.pth exp_name=LeMON exp_id=maml_11allev wandb.id=maml_11allev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=-1  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21normalall wandb.id=maml_21normalall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1 data.eval_types=-1  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21normalall/checkpoint.pth exp_name=LeMON exp_id=maml_21normalallev wandb.id=maml_21normalallev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21normalall/checkpoint.pth exp_name=LeMON exp_id=maml_21normalallev wandb.id=maml_21normalallev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON exp_id=maml_21fall wandb.id=maml_21fall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1 data.eval_types=-1  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21fall/checkpoint.pth exp_name=LeMON exp_id=maml_21allfev wandb.id=maml_21allfev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_21fall/checkpoint.pth exp_name=LeMON exp_id=maml_21allfev wandb.id=maml_21allfev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=-1 model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=LeMON exp_id=maml_fno_all wandb.id=maml_fno_all train_size_get=4500  train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_fno_all/checkpoint.pth exp_name=LeMON exp_id=maml_fno_allev wandb.id=maml_fno_allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=fno data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_fno_all/checkpoint.pth exp_name=LeMON exp_id=maml_fno_allev wandb.id=maml_fno_allev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=fno data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  data.random_idx=false exp_name=LeMON exp_id=maml_deeponet_all wandb.id=maml_deeponet_all train_size_get=4500  train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=-1  data.eval_types=-1 model.meta.gd_eta=0 model.meta.name=MAML model=deeponet  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_deeponet_all/checkpoint.pth exp_name=LeMON exp_id=maml_deeponet_allev wandb.id=maml_deeponet_allev eval_only=true  data.train_types=-1 train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=[conservation_cosflux]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/maml_deeponet_all/checkpoint.pth exp_name=LeMON exp_id=maml_deeponet_allev wandb.id=maml_deeponet_allev eval_only=true  data.train_types=-1 train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=-1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=10



type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_f wandb.id=maml21all_f train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_f/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fev wandb.id=maml21all_fev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20
#
CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fss wandb.id=maml21all_fss  train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.005
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fss /checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fssev wandb.id=maml21all_fssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.005

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11prosealllrsss wandb.id=maml_11prosealllrsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.0005
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrsss/checkpoint.pth exp_name=LeMON1 exp_id=maml_11prosealllrsssev wandb.id=maml_11prosealllrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fsss wandb.id=maml21all_fsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.0005
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fsss/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fssev wandb.id=maml21all_fssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.0005

