GPU=0

user=jingmins
#type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]

type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11proseall wandb.id=maml_11proseall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11proseall/checkpoint.pth exp_name=LeMON1 exp_id=maml_11proseallev wandb.id=maml_11proseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11prosealllrs wandb.id=maml_11prosealllrs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrs/checkpoint.pth exp_name=LeMON1 exp_id=maml_11prosealllrsev wandb.id=maml_11prosealllrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05

CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_learnlrall1_plotlr wandb.id=maml_11_learnlrall1_plotlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 print_outputs=true
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_learnlrall1/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_learnlrallev wandb.id=maml_11_learnlrallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_learnlrall1/checkpoint.pth exp_name=plot exp_id=maml_11_learnlrallevplot wandb.id=maml_11_learnlrallevplot eval_only=true   print_outputs=true  train_size=4900 train_size_get=1000 eval_size=1500 eval_size_get=1500 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11prosealllrss wandb.id=maml_11prosealllrss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrss/checkpoint.pth exp_name=LeMON1 exp_id=maml_11prosealllrssev wandb.id=maml_11prosealllrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrss/checkpoint.pth exp_name=plot exp_id=maml_11prosealllrssevplot wandb.id=maml_11prosealllrssevplot eval_only=true print_outputs=true   train_size=4900 train_size_get=1000 eval_size=1500 eval_size_get=1500 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=LeMON1 exp_id=reg_tproseall wandb.id=reg_tproseall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400  data.train_types=${type} data.eval_types=${type}  model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_tproseall/checkpoint.pth exp_name=LeMON1 exp_id=reg_tproseallev wandb.id=reg_tproseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${type} model.fusion.n_layer=1 zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=LeMON1 exp_id=reg_tprosenormalall wandb.id=reg_tprosenormalall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400  data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0  model.name=prose model.no_text=0 data.input_len=1 data.input_step=1 meta=0 zero_shot_only=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_tprosenormalall/checkpoint.pth exp_name=LeMON1 exp_id=reg_tprosenormalallev wandb.id=reg_tprosenormalallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=LeMON1 exp_id=reg_11proseall wandb.id=reg_11proseall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 zero_shot_only=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_11proseall/checkpoint.pth  exp_name=LeMON1 exp_id=reg_11proseallev wandb.id=reg_11proseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fnoall wandb.id=fnoall exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/fnoall/checkpoint.pth  exp_name=LeMON1 exp_id=fnoallev wandb.id=fnoallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponetall wandb.id=deeponetall exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/deeponetall/checkpoint.pth exp_name=LeMON1 exp_id=deeponetallev wandb.id=deeponetallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_fnoalls wandb.id=maml_fnoalls exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoalls/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoallsev wandb.id=maml_fnoallsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetall wandb.id=maml_deeponetall exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetallev wandb.id=maml_deeponetallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoalllrss wandb.id=maml_fnoalllrss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoalllrss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoalllrssev wandb.id=maml_fnoalllrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_f wandb.id=maml21all_f train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_f/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fev wandb.id=maml21all_fev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoalllrsss wandb.id=maml_fnoalllrsss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoalllrsss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoalllrsssev wandb.id=maml_fnoalllrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetalllrs wandb.id=maml_deeponetalllrs exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetalllrs/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetalllrsev wandb.id=maml_deeponetalllrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetalllrss wandb.id=maml_deeponetalllrss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetalllrss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetalllrssev wandb.id=maml_deeponetalllrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_learnlrall_4bs wandb.id=maml_11_learnlrall_4bs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=4 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_learnlrall_4bs/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_learnlrall_4bsev wandb.id=maml_11_learnlrall_4bsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_f wandb.id=maml21all_f train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_f/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fev wandb.id=maml21all_fev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fss wandb.id=maml21all_fss  train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fss /checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fssev wandb.id=maml21all_fssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fsss wandb.id=maml21all_fsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fsss/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fssev wandb.id=maml21all_fssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.0005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetalllrs wandb.id=maml_deeponetalllrs exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetalllrs/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetalllrsev wandb.id=maml_deeponetalllrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05


#train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]
#eval_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_tproseKG wandb.id=maml_tproseKG train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_tproseKG/checkpoint.pth exp_name=LeMON1 exp_id=maml_tproseKGev wandb.id=maml_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_proseKG wandb.id=maml_proseKG train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_proseKG/checkpoint.pth exp_name=LeMON1 exp_id=maml_proseKGev wandb.id=maml_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_tprosewave wandb.id=maml_tprosewave train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_tprosewave/checkpoint.pth exp_name=LeMON1 exp_id=maml_tprosewaveev wandb.id=maml_tprosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prosewave wandb.id=maml_prosewave train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prosewave/checkpoint.pth exp_name=LeMON1 exp_id=maml_prosewaveev wandb.id=maml_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_tprose wandb.id=maml_tprose train_size_get=4500 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_tprose/checkpoint.pth exp_name=LeMON1 exp_id=maml_tproseev wandb.id=maml_tproseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prose wandb.id=maml_prose train_size_get=4500 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prose/checkpoint.pth exp_name=LeMON1 exp_id=maml_proseev wandb.id=maml_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_tproseKG wandb.id=reg_tproseKG train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon]   model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_tproseKG/checkpoint.pth exp_name=LeMON1 exp_id=reg_tproseKGev wandb.id=reg_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_proseKG wandb.id=reg_proseKG train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon]  model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_proseKG/checkpoint.pth exp_name=LeMON1 exp_id=reg_proseKGev wandb.id=reg_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_tprosewave wandb.id=reg_tprosewave train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon]  model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_tprosewave/checkpoint.pth exp_name=LeMON1 exp_id=reg_tprosewaveev wandb.id=reg_tprosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_prosewave wandb.id=reg_prosewave train_size_get=81000 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon] model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_prosewave/checkpoint.pth exp_name=LeMON1 exp_id=reg_prosewaveev wandb.id=reg_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_tprose wandb.id=reg_tprose train_size_get=4500 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_tprose/checkpoint.pth exp_name=LeMON1 exp_id=reg_tproseev wandb.id=reg_tproseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_prose wandb.id=reg_prose train_size_get=4500 train_size=81000 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_prose/checkpoint.pth exp_name=LeMON1 exp_id=reg_proseev wandb.id=reg_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#

#cons_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux]
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11shock_cons wandb.id=maml_11shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/maml_11shock_cons/checkpoint.pth exp_name=LeMON exp_id=maml_11shock_consev wandb.id=maml_11shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_21shock_cons wandb.id=maml_21shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0 model.fusion.n_layer=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/maml_21shock_cons/checkpoint.pth exp_name=LeMON exp_id=maml_21shock_consev wandb.id=maml_21shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.fusion.n_layer=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_11shock_cons wandb.id=reg_11shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type}  model.name=prose model.no_text=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/reg_11shock_cons/checkpoint.pth exp_name=LeMON exp_id=reg_11shock_consev wandb.id=reg_11shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_21shock_cons wandb.id=reg_21shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} model.name=prose model.no_text=0 model.fusion.n_layer=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/reg_21shock_cons/checkpoint.pth exp_name=LeMON exp_id=reg_21shock_consev wandb.id=reg_21shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=one_shock data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.fusion.n_layer=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_112shock_cons wandb.id=maml_112shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/maml_112shock_cons/checkpoint.pth exp_name=LeMON exp_id=maml_112shock_consev wandb.id=maml_112shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_212shock_cons wandb.id=maml_212shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0 model.fusion.n_layer=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/maml_212shock_cons/checkpoint.pth exp_name=LeMON exp_id=maml_212shock_consev wandb.id=maml_212shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.fusion.n_layer=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_112shock_cons wandb.id=reg_112shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type}  model.name=prose model.no_text=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/reg_112shock_cons/checkpoint.pth exp_name=LeMON exp_id=reg_112shock_consev wandb.id=reg_112shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=reg_212shock_cons wandb.id=reg_212shock_cons train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} model.name=prose model.no_text=0 model.fusion.n_layer=1 num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/jingmins/dumped/LeMON1/reg_212shock_cons/checkpoint.pth exp_name=LeMON exp_id=reg_212shock_consev wandb.id=reg_212shock_consev eval_only=true data.train_types=${cons_type} data.eval_data=[one_shock,two_shocks,rarefaction] data.train_data=two_shocks data.eval_types=${cons_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.fusion.n_layer=1 model.name=prose zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetall_large_learnlr_plotlr wandb.id=maml_deeponetall_large_learnlr_plotlr exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet model.meta.learnable_lr=True   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.basis_dim=100 model.hidden_dim=256 print_outputs=true
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_learnlr/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetall_large_learnlrev wandb.id=maml_deeponetall_large_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_learnlr/checkpoint.pth  exp_name=plot exp_id=maml_deeponetall_large_learnlrevplot wandb.id=maml_deeponetall_large_learnlrevplot print_outputs=true eval_only=true   train_size=4900 train_size_get=4900 eval_size=1500 eval_size_get=1500 batch_size_task=5 meta=1 model.no_text=1 model=deeponet model.meta.learnable_lr=True  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256

#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetall_large_lrs wandb.id=maml_deeponetall_large_lrs exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet  data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML  model.meta.meta_lr=0.05 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrs/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetall_large_lrsev wandb.id=maml_deeponetall_large_lrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.05 model.basis_dim=100 model.hidden_dim=256
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetall_large_lrss wandb.id=maml_deeponetall_large_lrss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetall_large_lrssev wandb.id=maml_deeponetall_large_lrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrss/checkpoint.pth  exp_name=plot exp_id=maml_deeponetall_large_lrssevplot wandb.id=maml_deeponetall_large_lrssevplot print_outputs=true eval_only=true   train_size=4900 train_size_get=5500 eval_size=300 eval_size_get=300 batch_size_task=5 meta=1 model.no_text=1 model=deeponet data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256



#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetall_large_lrsss wandb.id=maml_deeponetall_large_lrsss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML  model.meta.meta_lr=0.0005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrsss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetall_large_lrsssev wandb.id=maml_deeponetall_large_lrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.0005 model.basis_dim=100 model.hidden_dim=256

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponetall_large wandb.id=deeponetall_large exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1 meta=0 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/deeponetall_large/checkpoint.pth exp_name=LeMON1 exp_id=deeponetall_largeev wandb.id=deeponetall_largeev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrss_bs5 wandb.id=maml_fnoall_large_lrss_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.005 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrss_bs5  exp_name=LeMON1 exp_id=maml_fnoall_large_lrss_bs5ev wandb.id=maml_fnoall_large_lrss_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005  model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrss_bs5  exp_name=plot exp_id=maml_fnoall_large_lrss_bs5evplot wandb.id=maml_fnoall_large_lrss_bs5evplot  print_outputs=true eval_only=true   train_size=4900 train_size_get=1000 eval_size=300 eval_size_get=300 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005  model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr/checkpoint.pth  exp_name=plot exp_id=maml_fnoall_large_learnlrevplot wandb.id=maml_fnoall_large_learnlrevplot eval_only=true   train_size=4900 train_size_get=1000 eval_size=300 eval_size_get=300 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128

#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrsss_bs5 wandb.id=maml_fnoall_large_lrsss_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.0005 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrsss_bs5 exp_name=LeMON1 exp_id=maml_fnoall_large_lrsss_bs5ev wandb.id=maml_fnoall_large_lrsss_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005  model.hidden_channels=128
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrs_bs5 wandb.id=maml_fnoall_large_lrs_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.05 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrs_bs5  exp_name=LeMON1 exp_id=maml_fnoall_large_lrs_bs5ev wandb.id=maml_fnoall_large_lrs_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05  model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrs_bs5  exp_name=plot exp_id=maml_fnoall_large_lrs_bs5evplot wandb.id=maml_fnoall_large_lrs_bs5evplot  print_outputs=true eval_only=true  train_size=4900 train_size_get=1000 eval_size=300 eval_size_get=300 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05  model.hidden_channels=128


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_lrs wandb.id=maml_extr3_11_lrs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_lrs/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_lrsev wandb.id=maml_extr3_11_lrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_lrsss wandb.id=maml_extr3_11_lrsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_lrsss/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_lrsssev wandb.id=maml_extr3_11_lrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005
