GPU=1

user=jingmins

#type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#


train_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave]
eval_type=[advection,conservation_sinflux,diff_bistablereact_1D,fplanck,heat,inviscid_conservation_cubicflux,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,conservation_cubicflux,inviscid_conservation_sinflux,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_learnlrall wandb.id=maml_11_learnlralltest train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_learnlrall/checkpoint.pth exp_name=plot exp_id=maml_11_learnlrallevplot wandb.id=maml_11_learnlrallevplot eval_only=true   print_outputs=true  train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrss/checkpoint.pth exp_name=plot exp_id=maml_11prosealllrssevplot wandb.id=maml_11prosealllrssevplot eval_only=true print_outputs=true   train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_learnlr/checkpoint.pth  exp_name=plot exp_id=maml_deeponetall_large_learnlrevplot wandb.id=maml_deeponetall_large_learnlrevplot print_outputs=true eval_only=true   train_size=4900 train_size_get=4900 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model=deeponet model.meta.learnable_lr=True  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrss/checkpoint.pth  exp_name=plot exp_id=maml_deeponetall_large_lrssevplot wandb.id=maml_deeponetall_large_lrssevplot print_outputs=true eval_only=true   train_size=4900 train_size_get=5500 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model=deeponet data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrss_bs5  exp_name=plot exp_id=maml_fnoall_large_lrss_bs5evplot wandb.id=maml_fnoall_large_lrss_bs5evplot  print_outputs=true eval_only=true   train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005  model.hidden_channels=128
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr/checkpoint.pth  exp_name=plot exp_id=maml_fnoall_large_learnlrevplot wandb.id=maml_fnoall_large_learnlrevplot eval_only=true print_outputs=true  train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_11proseall/checkpoint.pth  exp_name=plot exp_id=reg_11proseallevplot wandb.id=reg_11proseallevplot eval_only=true print_outputs=true  train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/fnoall_large/checkpoint.pth  exp_name=plot exp_id=fnoallevplot wandb.id=fnoallevplot eval_only=true print_outputs=true  train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/deeponetall_large/checkpoint.pth exp_name=plot exp_id=deeponetallevplot wandb.id=deeponetallevplot eval_only=true print_outputs=true   train_size=4900 train_size_get=1000 eval_size=50 eval_size_get=50 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=[Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/comparison2/11pretrain/checkpoint.pth exp_name=LeMON1 exp_id=reg_proseev wandb.id=reg_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/comparison2/21pretrain/checkpoint.pth exp_name=LeMON1 exp_id=reg_tproseev wandb.id=reg_tproseev eval_only=true  data.train_types=${train_type} train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/comparison2/11pretrain_KG/checkpoint.pth exp_name=LeMON1 exp_id=reg_proseKGev wandb.id=reg_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/comparison2/21pretrain_KG/checkpoint.pth exp_name=LeMON1 exp_id=reg_tproseKGev wandb.id=reg_tproseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Klein_Gordon,Sine_Gordon]  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/comparison2/11pretrain_wave/checkpoint.pth exp_name=LeMON1 exp_id=reg_prosewaveev wandb.id=reg_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave,Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/comparison2/21pretrain_wave/checkpoint.pth exp_name=LeMON1 exp_id=reg_tprosewaveev wandb.id=reg_tprosewaveev eval_only=true  data.train_types=[wave] train_size=1400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[wave,Sine_Gordon]  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_tprose wandb.id=maml_tprose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1  model.fusion.n_layer=1 optim.scheduler_type=inverse_sqrt
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_tprose/checkpoint.pth exp_name=LeMON1 exp_id=maml_tproseev wandb.id=maml_tproseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=[Sine_Gordon] model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prose wandb.id=maml_prose train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prose/checkpoint.pth exp_name=LeMON1 exp_id=maml_proseev wandb.id=maml_proseev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prose_learnlr wandb.id=maml_prose_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=[Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prose_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_prose_learnlrev wandb.id=maml_prose_learnlrev eval_only=true  data.train_types=${train_type} train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True  data.eval_types=[Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_proseKG wandb.id=maml_proseKG train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[Klein_Gordon] data.eval_types=[Klein_Gordon,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_proseKG/checkpoint.pth exp_name=LeMON1 exp_id=maml_proseKGev wandb.id=maml_proseKGev eval_only=true  data.train_types=[Klein_Gordon] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[Sine_Gordon]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_prosewave wandb.id=maml_prosewave train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=[wave] data.eval_types=[wave,Sine_Gordon]  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 optim.scheduler_type=inverse_sqrt model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_prosewave/checkpoint.pth exp_name=LeMON1 exp_id=maml_prosewaveev wandb.id=maml_prosewaveev eval_only=true  data.train_types=[wave] train_size=81400 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=[wave]  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05





type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_fnoalllr wandb.id=maml_fnoalllr exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno  model.meta.learnable_lr=True data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoalllr/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoalllrev wandb.id=maml_fnoalllrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetalllr wandb.id=maml_deeponetalllr exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet model.meta.learnable_lr=True   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetalllr/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetalllrev wandb.id=maml_deeponetalllrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetalllrsss wandb.id=maml_deeponetalllrsss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetalllrsss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetalllrsssev wandb.id=maml_deeponetalllrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetalllrs/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetalllrsev wandb.id=maml_deeponetalllrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11prosealllrsss wandb.id=maml_11prosealllrsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrsss/checkpoint.pth exp_name=LeMON1 exp_id=maml_11prosealllrsssev wandb.id=maml_11prosealllrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fs wandb.id=maml21all_fs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fs/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fsev wandb.id=maml21all_fsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.05


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoalllrsss wandb.id=maml_fnoalllrsss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoalllrsss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoalllrsssev wandb.id=maml_fnoalllrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11proseall/checkpoint.pth exp_name=LeMON1 exp_id=maml_11proseallev wandb.id=maml_11proseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_f/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fev wandb.id=maml21all_fev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fss/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fssev wandb.id=maml21all_fssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_11proseall/checkpoint.pth  exp_name=LeMON1 exp_id=reg_11proseallev wandb.id=reg_11proseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/fnoall/checkpoint.pth  exp_name=LeMON1 exp_id=fnoallev wandb.id=fnoallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/deeponetall/checkpoint.pth exp_name=LeMON1 exp_id=deeponetallev wandb.id=deeponetallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_fnoall_large_learnlr wandb.id=maml_fnoall_large_learnlr exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno  model.meta.learnable_lr=True data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_large_learnlrev wandb.id=maml_fnoall_large_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrs wandb.id=maml_fnoall_large_lrs exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.05 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrs/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_large_lrsev wandb.id=maml_fnoall_large_lrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05  model.hidden_channels=128

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrss wandb.id=maml_fnoall_large_lrss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.005 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_large_lrssev wandb.id=maml_fnoall_large_lrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005  model.hidden_channels=128

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrsss wandb.id=maml_fnoall_large_lrsss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.0005 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrsss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_large_lrsssev wandb.id=maml_fnoall_large_lrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005  model.hidden_channels=128

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=fnoall_large wandb.id=fnoall_large exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=0 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/fnoall_large/checkpoint.pth  exp_name=LeMON1 exp_id=fnoall_largeev wandb.id=fnoall_largeev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005 model.hidden_channels=128 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=maml_deeponetall_large_lrss wandb.id=maml_deeponetall_large_lrss exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrss/checkpoint.pth  exp_name=LeMON1 exp_id=maml_deeponetall_large_lrssev wandb.id=maml_deeponetall_large_lrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=deeponetall_large wandb.id=deeponetall_large exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1 meta=0 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/deeponetall_large/checkpoint.pth exp_name=LeMON1 exp_id=deeponetall_largeev wandb.id=deeponetall_largeev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256 model.meta.meta_lr=0.005

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_bs1_learnlr wandb.id=maml_11_ablation_bs1_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_bs1_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_bs1_learnlrev wandb.id=maml_11_ablation_bs1_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_bs2_learnlr wandb.id=maml_11_ablation_bs2_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=2 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_bs2_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_bs2_learnlrev wandb.id=maml_11_ablation_bs2_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_bs3_learnlr wandb.id=maml_11_ablation_bs3_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=3 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_bs3_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_bs3_learnlrev wandb.id=maml_11_ablation_bs3_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_bs4_learnlr wandb.id=maml_11_ablation_bs4_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=4 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_bs4_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_bs4_learnlrev wandb.id=maml_11_ablation_bs4_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_step1_learnlr wandb.id=maml_11_ablation_step1_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=1 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_step1_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_step1_learnlrev wandb.id=maml_11_ablation_step1_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_step2_learnlr wandb.id=maml_11_ablation_step2_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=2 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_step2_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_step2_learnlrev wandb.id=maml_11_ablation_step2_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_step3_learnlr wandb.id=maml_11_ablation_step3_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=3 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_step3_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_step3_learnlrev wandb.id=maml_11_ablation_step3_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11_ablation_step4_learnlr wandb.id=maml_11_ablation_step4_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=4 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11_ablation_step4_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_11_ablation_step4_learnlrev wandb.id=maml_11_ablation_step3_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_bs1_time wandb.id=ablation_bs1_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=1 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_bs2_time wandb.id=ablation_bs2_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=2 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_bs3_time wandb.id=ablation_bs3_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=3 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_bs4_time wandb.id=ablation_bs4_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=4 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_bs5_time wandb.id=ablation_bs5_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_step4_time wandb.id=ablation_step4_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=4 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_step3_time wandb.id=ablation_step3_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=3 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_step2_time wandb.id=ablation_step2_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=2 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=ablation_step1_time wandb.id=ablation_step1_time train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=1 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 max_epoch=1 n_steps_per_epoch=200



train_type=[advection,inviscid_burgers,inviscid_conservation_cubicflux,conservation_cubicflux,diff_bistablereact_1D,porous_medium,fplanck,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,wave,Sine_Gordon]
eval_type=[burgers,Klein_Gordon,diff_linearreact_1D,heat]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_fno exp_name=LeMON1 exp_id=maml_extr3_fnoev wandb.id=maml_extr3_fnoev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005

#train_type=[heat,inviscid_burgers,inviscid_conservation_cubicflux,conservation_cubicflux,inviscid_conservation_sinflux,conservation_sinflux]
#eval_type=[burgers]
##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extrcons_11_learnlr wandb.id=maml_extrcons_11_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extrcons_11_learnlr exp_name=LeMON1 exp_id=maml_extrcons_11_learnlrev wandb.id=maml_extrcons_11_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extrcons_11 wandb.id=maml_extrcons_11 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extrcons_11 exp_name=LeMON1 exp_id=maml_extrcons_11ev wandb.id=maml_extrcons_11ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=LeMON1 exp_id=reg_extrcons_21 wandb.id=reg_extrcons_21 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size=60 data.train_types=${train_type} data.eval_types=${eval_type}  model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1 zero_shot_only=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_extrcons_21 exp_name=LeMON1 exp_id=reg_extrcons_21ev wandb.id=reg_extrcons_21ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false  exp_id=maml_fnoall_large_learnlr_bs5 wandb.id=maml_fnoall_large_learnlr_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno  model.meta.learnable_lr=True data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr_bs5/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_large_learnlr_bs5ev wandb.id=maml_fnoall_large_learnlr_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetall_large_learnlr_bs5 wandb.id=maml_deeponetall_large_learnlr_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet model.meta.learnable_lr=True   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_learnlr_bs5 exp_name=LeMON1 exp_id=maml_deeponetall_large_learnlr_bs5ev wandb.id=maml_deeponetall_large_learnlr_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr_bs5  exp_name=LeMON1 exp_id=maml_fnoall_large_learnlr_bs5ev wandb.id=maml_fnoall_large_learnlr_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false  exp_id=maml_fnoall_large_learnlr_bs3 wandb.id=maml_fnoall_large_learnlr_bs3 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=3  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno  model.meta.learnable_lr=True data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr_bs3/checkpoint.pth  exp_name=LeMON1 exp_id=maml_fnoall_large_learnlr_bs3ev wandb.id=maml_fnoall_large_learnlr_bs3ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128

#

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrss_bs5 wandb.id=maml_fnoall_large_lrss_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.005 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrss_bs5  exp_name=LeMON1 exp_id=maml_fnoall_large_lrss_bs5ev wandb.id=maml_fnoall_large_lrss_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005  model.hidden_channels=128
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrsss_bs5 wandb.id=maml_fnoall_large_lrsss_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.0005 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrsss_bs5 exp_name=LeMON1 exp_id=maml_fnoall_large_lrsss_bs5ev wandb.id=maml_fnoall_large_lrsss_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005  model.hidden_channels=128
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_fnoall_large_lrs_bs5 wandb.id=maml_fnoall_large_lrs_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 data.train_types=${type}  data.eval_types=${type}  model=fno   data.input_len=1 data.input_step=1 meta=1  model.meta.gd_eta=0 model.meta.name=MAML model.meta.meta_lr=0.05 model.hidden_channels=128
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_lrs_bs5  exp_name=LeMON1 exp_id=maml_fnoall_large_lrs_bs5ev wandb.id=maml_fnoall_large_lrs_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05  model.hidden_channels=128


train_type=[advection,inviscid_burgers,inviscid_conservation_cubicflux,conservation_cubicflux,diff_bistablereact_1D,porous_medium,fplanck,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,wave,Sine_Gordon]
eval_type=[burgers,Klein_Gordon,diff_linearreact_1D,heat]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_lrs wandb.id=maml_extr3_11_lrs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_lrs/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_lrsev wandb.id=maml_extr3_11_lrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_21_lrss wandb.id=maml_extr3_21_lrss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_21_lrss/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_21_lrssev wandb.id=maml_extr3_21_lrssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_lrsss wandb.id=maml_extr3_11_lrsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_lrsss/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_lrsssev wandb.id=maml_extr3_11_lrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005
