GPU=1

user=jingmins

#type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]


#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fss_bs1 wandb.id=maml21all_fss_bs1  train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=2 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fss_bs1/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fssev wandb.id=maml21all_fssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.005

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml21all_fs wandb.id=maml21all_fs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.fusion.n_layer=1  model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml21all_fs/checkpoint.pth exp_name=LeMON1 exp_id=maml21all_fsev wandb.id=maml21all_fsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.fusion.n_layer=1  meta_step_eval=20 model.meta.meta_lr=0.05

#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_11prosealllrsss wandb.id=maml_11prosealllrsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_11prosealllrsss/checkpoint.pth exp_name=LeMON1 exp_id=maml_11prosealllrsssev wandb.id=maml_11prosealllrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005

#pre_train_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux]
#eval_type=[conservation_sinflux,inviscid_conservation_cubicflux,inviscid_conservation_sinflux,conservation_cubicflux,inviscid_burgers,burgers,conservation_cosflux,inviscid_conservation_cosflux,conservation_randomflux,inviscid_conservation_randomflux]
#eval_data=[one_shock,two_shocks,rarefaction,reg]
##
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/112shock_cons/checkpoint.pth exp_name=LeMON exp_id=112shock_cons1ev wandb.id=112shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/112shock_cons/checkpoint.pth exp_name=LeMON exp_id=112shock_cons1ev wandb.id=112shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/212shock_cons/checkpoint.pth exp_name=LeMON exp_id=212shock_cons1ev wandb.id=212shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/212shock_cons/checkpoint.pth exp_name=LeMON exp_id=212shock_cons1ev wandb.id=212shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=two_shocks data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11shock_cons/checkpoint.pth exp_name=LeMON exp_id=11shock_cons1ev wandb.id=11shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/11shock_cons/checkpoint.pth exp_name=LeMON exp_id=11shock_cons1ev wandb.id=11shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=1 meta=1 model.no_text=1 model.name=prose  zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=10
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21shock_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_cons1ev wandb.id=21shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON/21shock_cons/checkpoint.pth exp_name=LeMON exp_id=21shock_cons1ev wandb.id=21shock_cons1ev eval_only=true  data.train_types=${pre_train_type} data.eval_data=${eval_data}  data.train_data=one_shock data.eval_types=${pre_train_type} train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=0 model.no_text=0 model.name=prose  model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 model.meta.meta_lr=0.01 meta_step_eval=10


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_name=LeMON1 exp_id=reg_11proseall wandb.id=reg_11proseall train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${type} data.eval_types=${type}  model.meta.gd_eta=0 model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 zero_shot_only=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_11proseall/checkpoint.pth  exp_name=LeMON1 exp_id=reg_11proseallev wandb.id=reg_11proseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_tproseall/checkpoint.pth exp_name=LeMON1 exp_id=reg_tproseallev wandb.id=reg_tproseallev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose  data.eval_types=${type} model.fusion.n_layer=1 zero_shot_only=1 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005


#
#train_type=[advection,diff_bistablereact_1D,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,cahnhilliard_1D,kdv,diff_logisreact_1D,wave]
#eval_type=[burgers,Sine_Gordon,diff_squarelogisticreact_1D,porous_medium,fplanck]

#
#train_type=[inviscid_burgers,heat,diff_bistablereact_1D,porous_medium,fplanck,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,wave,Sine_Gordon]
#eval_type=[burgers,Klein_Gordon,diff_linearreact_1D,advection]

train_type=[advection,inviscid_burgers,inviscid_conservation_cubicflux,conservation_cubicflux,diff_bistablereact_1D,porous_medium,fplanck,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,wave,Sine_Gordon]
eval_type=[burgers,Klein_Gordon,diff_linearreact_1D,heat]

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_learnlr wandb.id=maml_extr3_11_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_learnlrev wandb.id=maml_extr3_11_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_deeponet_learnlr wandb.id=maml_extr3_deeponet_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model=deeponet model.meta.learnable_lr=True  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_deeponet_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_deeponet_learnlrev wandb.id=maml_extr3_deeponet_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet model.meta.learnable_lr=True data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_fno_learnlr wandb.id=maml_extr3_fno_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model=fno model.meta.learnable_lr=True  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_fno_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_fno_learnlrev wandb.id=maml_extr3_fno_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_fno_learnlr2 wandb.id=maml_extr3_fno_learnlr2 base_seed=10011 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model=fno model.meta.learnable_lr=True  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_fno_learnlr2/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_fno_learnlr2ev wandb.id=maml_extr3_fno_learnlr2ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_deeponet wandb.id=maml_extr3_deeponet train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model=deeponet   num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_deeponet/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_deeponetev wandb.id=maml_extr3_deeponetev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model=deeponet data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#
#type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_fnoall_large_learnlr_bs5 exp_name=LeMON1 exp_id=maml_fnoall_large_learnlr_bs5ev wandb.id=maml_fnoall_large_learnlr_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno model.meta.learnable_lr=True  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.hidden_channels=128
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_fno wandb.id=maml_extr3_fno train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model=fno  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_fno/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_fnoev wandb.id=maml_extr3_fnoev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11 wandb.id=maml_extr3_11 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11ev wandb.id=maml_extr3_11ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=LeMON1 exp_id=reg_extr3_21 wandb.id=reg_extr3_21_ train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size=60 data.train_types=${train_type} data.eval_types=${eval_type}  model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1 zero_shot_only=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_extr3_21/checkpoint.pth exp_name=LeMON1 exp_id=reg_extr3_21ev wandb.id=reg_extr3_21ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=LeMON1 exp_id=reg_extr3_11 wandb.id=reg_extr3_11 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size=512 data.train_types=${train_type} data.eval_types=${eval_type}  model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0 zero_shot_only=1
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_extr3_11/checkpoint.pth exp_name=LeMON1 exp_id=reg_extr3_11ev wandb.id=reg_extr3_11ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=reg_extr3_fno wandb.id=reg_extr3_fno exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${train_type}  data.eval_types=${eval_type}  model=fno   data.input_len=1 data.input_step=1 meta=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_extr3_fno/checkpoint.pth  exp_name=LeMON1 exp_id=reg_extr3_fnoev wandb.id=reg_extr3_fnoev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=fno  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005

#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 exp_id=reg_extr3_deeponet wandb.id=reg_extr3_deeponet exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size=512  zero_shot_only=1 meta=0 data.train_types=${eval_type} data.eval_types=${eval_type} model=deeponet   data.input_len=1 data.input_step=1 meta=0
CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_extr3_deeponet/checkpoint.pth exp_name=LeMON1 exp_id=reg_extr3_deeponetev wandb.id=reg_extr3_deeponetev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
 ##
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_lrs wandb.id=maml_extr3_11_lrs train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.05
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_lrs/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_lrsev wandb.id=maml_extr3_11_lrsev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.05
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extr3_11_lrsss wandb.id=maml_extr3_11_lrsss train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.0005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extr3_11_lrsss/checkpoint.pth exp_name=LeMON1 exp_id=maml_extr3_11_lrsssev wandb.id=maml_extr3_11_lrsssev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.0005

#
#train_type=[heat,inviscid_burgers,inviscid_conservation_cubicflux,conservation_cubicflux,inviscid_conservation_sinflux,conservation_sinflux,inviscid_conservation_cosflux,conservation_cosflux]
#eval_type=[burgers]
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extrcons_11_learnlr wandb.id=maml_extrcons_11_learnlr train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose_freeze_symbol model.meta.learnable_lr=True model.no_text=0 model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extrcons_11_learnlr/checkpoint.pth exp_name=LeMON1 exp_id=maml_extrcons_11_learnlrev wandb.id=maml_extrcons_11_learnlrev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose_freeze_symbol model.meta.learnable_lr=True data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_name=LeMON1 exp_id=maml_extrcons_11 wandb.id=maml_extrcons_11 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size_task=5 meta_step=5 data.train_types=${train_type} data.eval_types=${eval_type}  model.meta.gd_eta=0 model.meta.name=MAML model.name=prose model.no_text=1  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=1 model.meta.meta_lr=0.005
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_extrcons_11/checkpoint.pth exp_name=LeMON1 exp_id=maml_extrcons_11ev wandb.id=maml_extrcons_11ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model.name=prose  data.eval_types=${eval_type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20 model.meta.meta_lr=0.005
#
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256  exp_name=LeMON1 exp_id=reg_extrcons_21 wandb.id=reg_extrcons_21 train_size_get=4500 train_size=4500 eval_size=400 eval_size_get=400 batch_size=60 data.train_types=${train_type} data.eval_types=${eval_type}  model.name=prose model.no_text=0  num_adapt_eval=5 data.input_len=1 data.input_step=1 meta=0  model.fusion.n_layer=1 zero_shot_only=1
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/reg_extrcons_21/checkpoint.pth exp_name=LeMON1 exp_id=reg_extrcons_21ev wandb.id=reg_extrcons_21ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=0 model.name=prose_freeze_symbol  data.eval_types=${eval_type} model.fusion.n_layer=1 zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20
#

type=[advection,diff_bistablereact_1D,fplanck,heat,Klein_Gordon,diff_linearreact_1D,inviscid_burgers,burgers,diff_squarelogisticreact_1D,cahnhilliard_1D,kdv,diff_logisreact_1D,porous_medium,wave,Sine_Gordon]
#


#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetall_large_lrss_bs5 wandb.id=maml_deeponetall_large_lrss_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrss_bs5  exp_name=LeMON1 exp_id=maml_deeponetall_large_lrss_bs5ev wandb.id=maml_deeponetall_large_lrss_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.005 model.basis_dim=100 model.hidden_dim=256
#
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py batch_size_eval=256 data.random_idx=false exp_id=maml_deeponetall_large_lrsss_bs5 wandb.id=maml_deeponetall_large_lrsss_bs5 exp_name=LeMON1 train_size=4500 eval_size=400 eval_size_get=400 train_size_get=4500 batch_size_task=5  zero_shot_only=0 meta=1 data.train_types=${type} data.eval_types=${type} model=deeponet   data.input_len=1 data.input_step=1  model.meta.gd_eta=0 model.meta.name=MAML  model.meta.meta_lr=0.0005 model.basis_dim=100 model.hidden_dim=256
#CUDA_VISIBLE_DEVICES=$GPU python src/main.py  batch_size_eval=256 data.random_idx=false eval_from_exp=checkpoint/${user}/dumped/LeMON1/maml_deeponetall_large_lrsss_bs5 exp_name=LeMON1 exp_id=maml_deeponetall_large_lrsss_bs5ev wandb.id=maml_deeponetall_large_lrsss_bs5ev eval_only=true   train_size=4900 train_size_get=1000 eval_size=4000 eval_size_get=4000 batch_size_task=5 meta=1 model.no_text=1 model=deeponet  data.eval_types=${type} zero_shot_only=0 data.input_len=1 data.input_step=1 noise=0 meta_step_eval=20  model.meta.meta_lr=0.0005 model.basis_dim=100 model.hidden_dim=256

